### ISSUE TITLE
DPL-558 [Traction] Classify the barcodes based on their relevant tag sets when creating a new sample library

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/traction-ui#1023]
**User story**
As a QC user from the Long Read team, I WANT to view a clear classification of barcodes displayed for selection when creating a new sample Library in Traction SO THAT, we can avoid re-processing of the samples due to incorrect barcode selection.

** Description**
The QC Team has highlighted that due to similar names and presentation of the barcode values the user tends to select a barcode value belonging to a different Tag Set that is not applicable for the current sample library being created from the Sample> Create Library modal window. This error was highlighted as a HIGH severity issue during their team's issue root cause analysis exercise. 
It was also observed that such concerns are highlighted by the SMRT Link system only later in the processing pipeline, leading to reprocessing of the samples. 
A solution where the users can clearly distinguish between the various barcode groups listed in the drop-down would help them to avoid such manual errors. A similar option of selecting tags based on their specific grouping is currently also available in Libraries > Edit screen

**Who are the primary contacts for this story**
James Watt

**Who is the nominated tester for UAT**
James Watt

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Confirm whether I can navigate to the Sample > Create library screen and continue to view an option to select applicable tags for the sample library.
- [x] Confirm whether I can view the tag selection option updated to display a clear distinction/classification between the various barcodes corresponding to their respective family of tag-sets 
- [x] Confirm whether I can select the appropriate barcode value for the sample library
- [x] Confirm whether the selected tag-barcode value is saved successfully against the new sample library

**Dependencies**
This story is blocked by the following dependencies:
- None

References
This story has a non-blocking relationship with:
- None

**Additional context**
Current implementation on Libraries > Edit screen:
![image](https://user-images.githubusercontent.com/115623404/200885998-2c67f9b2-84ce-4136-a44d-7ef53faea933.png)

Solution option suggested by James Watt:
![DPL558](https://user-images.githubusercontent.com/115623404/201324533-63b5a51a-0e17-429d-86b3-ce0f96ab6959.png)

**Comment by yoldas** [comment]
Attached screenshots

<img width="951" alt="Screenshot 2023-02-02 at 02 36 28" src="https://user-images.githubusercontent.com/91894/216217440-f1cfaf75-790d-47af-9960-3071db1a5a59.png">
<img width="951" alt="Screenshot 2023-02-02 at 02 36 34" src="https://user-images.githubusercontent.com/91894/216217480-5d5b01e5-fc4f-4a49-94fa-9e535e9737b2.png">
<img width="951" alt="Screenshot 2023-02-02 at 02 36 43" src="https://user-images.githubusercontent.com/91894/216217499-4b2c8e73-0f95-4797-8f26-09e4c5f216f9.png">
