### ISSUE TITLE
DPL-727 Custom component to replace b-form-group

### ISSUE THREAD

**Issue by seenanair** [sanger/traction-ui#1118]
**User story**
As part of clean migration from bootstrap (DPL-483) , create a custom component  to replace the bootstrap b-form-group using html fieldset

**Who are the primary contacts for this story**
Steve/Seena

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] The new component should contain all existing functionalities of b-form-group
- [ ] Support all existing features of b-form-group
- [ ] Compatibility with bootstrap props
- [ ] Feature flag support
- [ ] Replace all existing b-form-group references with new component
- [ ] Remove b-form-group from globally imported list

References
This story has a non-blocking relationship with:
- #827

**Comment by enegoktan** [comment]
Will check whether it is possible to use the html <fieldset> tag directly instead, to avoid creating a custom component.
