### ISSUE TITLE
DPL-746-1 - As a user I need to be able to add samples to 2 plates when I am creating a run for SMRT Link 12 for Revio (VueX Store)

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1131]
**User story**
As a user I need to be able to add samples to 2 plates when I am creating a run for SMRT Link 12 for Revio. VueX store changes only

**Who are the primary contacts for this story**
James / Craig / Steve

**Who is the nominated tester for UAT**
James / Craig

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Get, create, update runs, with multiple plates

**Dependencies**
This story is blocked by the following dependencies:
- #1133 

References
This story has a non-blocking relationship with:
- #1132 
- #1225

**Additional context**

**Comment by harrietc52** [comment]
**Tasks**

- Change the VueX store to look like the below, and get the current implementation working
```
{
  "state":{
    "run":{
      "plates":[
        {
          plate_attr_1: "",
          "wells": {
            "pools": {}
          }
        },
        {
          plate_attr_1: "",
          "wells": {
            "pools": {}
          }
        }
      ]
    }
  }
}
```

**Comment by harrietc52** [comment]
`src/store/traction/pacbio/runCreate/actions.js`

- `fetchRun` in include plate in request, and commit 'populateRun'
- `saveRun` just include run (which should include the plate/wells)
- `getOrCreateWell` gets wells from run.plate not wells

`src/store/traction/pacbio/runCreate/getters`
- `pools` ??
- `getWell`

`src/store/traction/pacbio/runCreate/mutations`
- `populateRun`
- `populatePools`
- `setPools`
- `removePool`
- `updateWell`
- `deleteWell`

`src/store/traction/pacbio/runCreate/run.js`

**Comment by harrietc52** [comment]
**Dependencies**
Traction Service branch: `976-dpl-740-modify-the-pacbio-run-to-have-more-than-one-plate-for-multi-plate-support`
https://github.com/sanger/traction-service/pull/1019
