### ISSUE TITLE
DPL-746-2 - As a user I need to be able to add samples to 2 plates when I am creating a run for SMRT Link 12 for Revio (UI component) 

### ISSUE THREAD

**Issue by harrietc52** [sanger/traction-ui#1225]
**User story**
As a user I need to be able to add samples to 2 plates when I am creating a run for SMRT Link 12 for Revio

**Who are the primary contacts for this story**
James / Craig / Steve

**Who is the nominated tester for UAT**
James / Craig

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] When I select SMRT Link 11 I will be able to add samples to a single plate in any well
- [ ] When I select SMRT Link 12 for Revio I will be able to add samples to 2 plates in selected wells

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/traction-ui/issues/1131

**Comment by harrietc52** [comment]
**Some possible improvements from developer UAT**

- For an existing Revio run with two plates, if you delete the all wells from one of the two plates, the validation fails. Not sure what we want to do in this case? For example, for https://uat.traction.psd.sanger.ac.uk/#/pacbio/run/47, try removing Plate 2 C1, and update. 

Steve: This would make sense as you can’t have a plate without wells. I suppose we could give them the option to delete a plate but we would need to change the service. Might be worth waiting for Long read to do UAT to see if it is an issue.

- And is it correct Revio v11 has the same Well attributes as Sequel IIe, but Revio v12 has difference well attributes

Steve: There is no v11 for Revio. I think we should restrict SMRT Link version for System but again we can wait until they do UAT to see if it cause issues.  Things we can do: 1) add validation to the service
2) modify the ui using the store so that when they select Revio or Sequel IIe it limits it to available SMRT Link Versions.

**Comment by BenTopping** [comment]
Closing as in Done column
