### ISSUE TITLE
DPL-805 Display serial number on run show page for revio plates

### ISSUE THREAD

**Issue by BenTopping** [sanger/traction-ui#1239]
**User story**
As a user (Craig) I would like the serial number to be displayed on the run show page for revio plates. The serial number is a subsection of the sequencing plate barcode. See attached images.

The scanned barcode for the Revio sequencing plate is 28 characters:
e.g.
1021188000301570037320231019
 
The serial number is characters 16 to 20:
e.g.
102118800030157**00373**20231019

**Who are the primary contacts for this story**
Craig C

**Who is the nominated tester for UAT**
Craig C

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] when i edit or create a sequencing run for revio the serial number should be displayed

**Additional context**

![2plate_traction1](https://github.com/sanger/traction-ui/assets/54811755/86400ab3-26f0-4eff-833c-4b825a286c85)

**Comment by SujitDey2022** [comment]
@BenTopping I have moved this to Triage to prioritise in the next meeting.

**Comment by harrietc52** [comment]
**Deployment**

To UAT:
`ansible-playbook -vD deploy_traction_ui.yml -i environments/uat -e "github_branch=v7.0.0-5522014790-develop"`
