### ISSUE TITLE
DPL-756-3 - As developers we need to modify pacbio run so the ui shows 2 plates rather than 1 when sample sheets and messaging are ready for multi-plate support

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1241]
**User story**
As developers we need to modify pacbio run so the ui shows 2 plates rather than 1 when sample sheets and messaging are ready for multi-plate support

**Who are the primary contacts for this story**
Ben / Steve / Harry / Stephen

**Who is the nominated tester for UAT**
Long Read

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Modify pacbio run systems config so Revio has 2 plates
- [x] Modify pacbio run tests to support 2 plates rather than 1

**Dependencies**
This story is blocked by the following dependencies:
- sanger/traction-service#993
- sanger/traction-service#992

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/t#<issue_no.>

**Additional context**

**Comment by harrietc52** [comment]
Only merge once DPL-745 is ready.
Until then, deploy from branch to test DPL-744 and DPL-764.
Once tested, deploy to UAT previous release with 1 plate for Revio Run. 

- Existing Traction UI version (v)
- Manually build release from branch
- Deployment
`ansible-playbook -vD deploy_traction_ui.yml -i environments/uat -e "github_branch=v<release>"`
