### ISSUE TITLE
DPL-814 SMRTLink v12 UI support for Sequel IIe

### ISSUE THREAD

**Issue by BenTopping** [sanger/traction-ui#1249]
**User story**
As a user (Craig C) I would like to remove 'DNA Control Complex Box Barcode’ from the PacBio run setup if it is a SMRTLink v12 run as the lab no longer have a barcode to scan.

**Who are the primary contacts for this story**
Ben T, Craig C

**Who is the nominated tester for UAT**
Craig C

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Hide ‘DNA Control Complex Box Barcode’ from the V12 PacBio run setup as the lab no longer have a barcode to scan.
- [x] Show 'DNA Control Complex Box Barcode' for old runs and V11 PacBio runs
- [x] Show well defaults correctly for v12_sequel_iie smrtlink. (may need to confirm these but should be same as v11)

**Additional context**
There is an element of service work in here as the DNA control complex box barcode is validated in the service. My advice would be to add a filter to the existing validation so that it only validates the DNA control complex barcode when it is a v11 run.

Dependent on https://github.com/sanger/traction-service/issues/1051.

**Comment by harrietc52** [comment]
## Deployment

(Don't deploy until https://github.com/sanger/traction-service/issues/1051 is ready)
