### ISSUE TITLE
DPL-850 - Investigate the work required to replace VueX with Pinia as the state management library

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1279]
**Description**
Investigate the work required to replace VueX with Pinia as the state management library. 

We currently use VueX but Pinia has now become the defacto recommended state management library for Vue 3. It is more lightweight, removes the need for mutations, allows for multiple stores (fits better with traction) and provides out of the box support for Typescript.

This would allow us to remove technical debt and support a move to typescript which should reduce maintenance and bugs across the board.

It would also allow us to standardise how we use the store throughout traction.

**Who the primary contacts are for this work**
Steve

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
[Pinia](https://pinia.vuejs.org/)

**Comment by seenanair** [comment]
@stevieing  @BenTopping  VueX to Pinia migration notes
[VueX to Pinia.docx](https://github.com/sanger/traction-ui/files/12496948/VueX.to.Pinia.docx)

**Comment by stevieing** [comment]
Closed as done.
