### ISSUE TITLE
DPL-871 -  As a developer I would like the ability to view old runs in Traction

### ISSUE THREAD

**Issue by BenTopping** [sanger/traction-ui#1300]
**User story**
As a developer I would like to add a fall back option for SMRTLink Versions and System Names so that old PacBio runs in Traction can still be viewed. Currently if you go to Traction production and try view an old run (TRACTION-RUN1), it errors when you try and view the run.

**Who are the primary contacts for this story**
Ben T

**Who is the nominated tester for UAT**
Ben T

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] When I go to a run with no SMRTLink Version or System Name I can still see the run plate and wells

**Comment by KatyTaylor** [comment]
@BenTopping 
So do we want to populate these fields for old runs with the correct information? 

Or do we want to leave them blank, and make the code handle it?

Thanks

**Comment by BenTopping** [comment]
> @BenTopping So do we want to populate these fields for old runs with the correct information?
> 
> Or do we want to leave them blank, and make the code handle it?
> 
> Thanks

@KatyTaylor 
Depends how tricky it is to populate them with the correct information. I would say that populating them is the preferred way because it provides more useful information about a run, but at the same time if some of the data doesn't exist in traction-service (like system name or smrt link version) Traction will reject any updates to the run anyway.

So I guess my answer is populate them if its fairly easy to do, but if it requires a large amount of work then just leave them blank and make the code handle it and it is not that much more valuable to populate them.

**Comment by KatyTaylor** [comment]
The 4 system names referenced in pacbio > run.rb (traction service) are Sequel II, Sequel I, Sequel IIe and Revio.
There aren't any Sequel I runs in the database.
```
SELECT system_name, IF(system_name = 0, "Sequel II", IF(system_name = 1, "Sequel I", IF(system_name = 2, "Sequel IIe", "Revio"))) AS system_name, COUNT(*) AS num_runs
FROM pacbio_runs
GROUP BY system_name;
```
![Screenshot 2023-10-05 at 14 50 18](https://github.com/sanger/traction-ui/assets/10407809/fdfc0e92-5bce-4b77-b3c4-324512bbefe7)

**Comment by KatyTaylor** [comment]
Before and after, having changed run 3 in the test data to have System Name "Sequel II", and SMRT Link Version "v10".
The reason no fields display for the Well Defaults section is that there are no fields configured for SMRT Link v10 in config > PacbioRunWellComponents.json - assume this is intended, or at least out of scope.

Before:
![Screenshot 2023-10-05 at 15 47 20](https://github.com/sanger/traction-ui/assets/10407809/684c499b-7971-43cc-9514-b3513dc1c62e)


After:
![Screenshot 2023-10-05 at 15 16 42](https://github.com/sanger/traction-ui/assets/10407809/75fced21-e012-4a43-be0e-e94fd1f914f8)

**Comment by KatyTaylor** [comment]
PRs: 
- https://github.com/sanger/traction-service/pull/1123
- https://github.com/sanger/traction-ui/pull/1355/files
