### ISSUE TITLE
DPL-895 Convert VueX module pacbio/tubes to Pinia store

### ISSUE THREAD

**Issue by seenanair** [sanger/traction-ui#1328]
**User story**
As Pinia has now become the defacto recommended state management library for Vue 3, we are planning to migrate from VueX to Pinia.  As part of clean migration, the conversion is planned module by module from VueX to Pinia.

- [ ] Create Pinia directory (stores)
- [ ] For VueX module pacbio/tubes
    - Convert to a  Pinia store with id same as namespace in Vuex 
    - Convert state, getters, action
    - Remove mutation
- [ ] Convert  usage inside components

*  Use Options API support of Pinia to maintain the existing code as much as possible

**Acceptance criteria**
To be considered successful the solution must allow replacement of Vuex module pacbio/tubes to Pinia store

**Who are the primary contacts for this story**
Steve/Seena

**Additional context**
This story has a non-blocking relationship with: 
#1327 
#1279 
#1326
References
[Pinia]
[Migration (https://pinia.vuejs.org/)]
[Migration] (https://pinia.vuejs.org/cookbook/migration-vuex.html)

**Comment by stevieing** [comment]
Closed as done.
