### ISSUE TITLE
DPL-950 - As a Long Read Samples Extraction user (Hermione) I would like to be able to import NT barcodes directly into Traction without using Samples Extraction to remove a dependency and save time

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1376]
**User story**
As a Long Read Samples Extraction user (Hermione) I would like to be able to import NT barcodes directly into Traction without using Samples Extraction to remove a dependency and save time

**Who are the primary contacts for this story**
Hermione / Steve

**Who is the nominated tester for UAT**
Hermione / Long Read

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] when visiting the reception page there should be an option to import tubes from Sequencescape OR to modify the reception to import plates and tubes together (ideal)
- [x] Users should be able to import multiple tubes
- [x] When those tubes are imported the human readable barcode (NT) should be used (not ean13 barcode)
- [x] The user to be able to reprint the barcodes using the existing traction template.
- [x] update Resolve Operations to improve performance https://vitejs.dev/guide/performance.html

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/General-Backlog-Items#316

**Additional context**

**Comment by seenanair** [comment]
Mockup
[Reception_Sequencescape_tubes.pdf](https://github.com/sanger/traction-ui/files/13526485/Reception_Sequencescape_tubes.pdf)

**Comment by seenanair** [comment]
[Sequence flow diagram]([https://lucid.app/lucidchart/8aa5260a-eb96-4c14-9578-c69309e74e2d/edit?viewport_l[…]1988%2C0_0&invitationId=inv_7b0b4ec8-8184-4263-bee0-3a5a5fe3485b](https://lucid.app/lucidchart/8aa5260a-eb96-4c14-9578-c69309e74e2d/edit?viewport_loc=2877%2C-1405%2C3544%2C1988%2C0_0&invitationId=inv_7b0b4ec8-8184-4263-bee0-3a5a5fe3485b)l)
