### ISSUE TITLE
DPL-992 - As a long read user I would like to be able to create libraries that are not pools because this fits with our lab process and will support Revio multiplexing

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1418]
**User story**
As a long read user I would like to be able to create libraries that are not pools because this fits with our lab process and will support Revio multiplexing

**Who are the primary contacts for this story**
James / Steve

**Who is the nominated tester for UAT**
James / Long Read

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] when I visit the libraries page I should only see libraries and not libraries that have been created as part of pools
- [ ] when I create a library it should not become part of a pool
- [ ] when I edit a library it will not redirect to the pools edit page
- [ ] update Resolve Operations to improve performance https://vitejs.dev/guide/performance.html

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- sanger/traction-service#1137
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by SujitDey2022** [comment]
@seenanair @stevieing to review the user-story

**Comment by stevieing** [comment]
Closed as being done within https://github.com/sanger/traction-ui/issues/1509, https://github.com/sanger/traction-ui/issues/1511 and https://github.com/sanger/traction-ui/issues/1421
