### ISSUE TITLE
DPL-993 - As a long read user when I create a pool I would like to be able to add samples or libraries as it fits in better with our lab processes and will support Revio multiplexing

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1419]
**User story**
As a long read user when I create a pool I would like to be able to add samples or libraries as it fits in better with our lab processes and will support Revio multiplexing

**Who are the primary contacts for this story**
James / Steve

**Who is the nominated tester for UAT**
James / Long Read

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] when I visit the new pool page I should be able to select samples from plates (scanning barcodes)
- [x] when I visit the new pool page I should be able to select samples from tubes (scanning barcodes)
- [x] when I visit the new pool page I should be able to select libraries (scanning barcodes)
- [x] when I select a library it should copy the metadata (volume, concentration, insert size and template prep kit box barcode)
- [x] when I select a library I should be able to modify the metadata
- [x] when I select a library it should show the library barcode
- [x] I should be able to add tags to libraries when I select them
- [x] when I select a library I should be able to see the barcode
- [ ] I should not be able to delete a library from the libraries page that is part of a pool.

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #sanger/traction-service#1137
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
@BenTopping and @seenanair it might also be useful to do this story as part of this work:
- #1332

**Comment by BenTopping** [comment]
Closing as in done.
