### ISSUE TITLE
DPL-995 - As a developer I need to modify library creation so that it does not create a pool of 1 as this fits better with the lab process and supports revio multiplexing

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1421]
**User story**
As a developer I need to modify library creation so that it does not create a pool of 1 as this fits better with the lab process and supports revio multiplexing

**Who are the primary contacts for this story**
James / Steve

**Who is the nominated tester for UAT**
James / Long Read

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] moving the pacbio library creation store to Pinia
- [ ] modifying the library creation process so it creates a library and not a pool of 1 library.
- [ ] update Resolve Operations to improve performance https://vitejs.dev/guide/performance.html

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- sanger/traction-service#1137
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by TWJW-SANGER** [comment]
Coming at this with little understanding - I see "modifying the library creation process so it doesn't create a pool of 1" (aliquot?) but I am not sure what it _should_ create?
