### ISSUE TITLE
DPL-996 - As developers we need to modify the pool creation process so it can contain request or libraries and creates aliquots as this better fits with the lab process and supports Revio multiplexing

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1422]
**User story**
As developers we need to modify the pool creation process so it can contain request or libraries and creates aliquots as this better fits with the lab process and supports Revio multiplexing

**Who are the primary contacts for this story**
James / Steve

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] move pool creation and pool edit to Pinia
- [ ] modify actions for creating and updating pools to create aliquots rather than libraries
- [ ] modify payload that is sent to the API to send aliquots rather than libraries
- [ ] update Resolve Operations to improve performance https://vitejs.dev/guide/performance.html

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #sanger/traction-service#1137
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by BenTopping** [comment]
Closing as in done
