### ISSUE TITLE
Y24-045 ONT Pool creation page improvement on usability 

### ISSUE THREAD

**Issue by seenanair** [sanger/traction-ui#1606]
**User story**
Improvement to ONT pool create page so the process of adding tubes to pool is more obvious

**Who are the primary contacts for this story**
William K

**Who is the nominated tester for UAT**
William K

**Acceptance criteria**
To be considered successful the solution must allow:
The user must be able to add/remove samples from selected tubes

Potential solutions are 

[ ] adding a 'Add' button to the 'Actions' column of the selected tubes table
[ ] auto adding samples in tube to the pool when it is scanned in.
[ ] Adding a hint / description to the selected tubes area. 
Or
[] Use the same UI enhancements done on Pacbio Pool create page

**Dependencies**
- #1332

References
This story has a non-blocking relationship with:
- #1332

**Additional context**

**Comment by stevieing** [comment]
@seenanair I am slightly confused by this story. Currently you can't pool from tubes in ONT?

**Comment by seenanair** [comment]
@stevieing This is about Pool/new page where we scan tubes in ONT pipeline which is shown in screenshot below. Does it make sense? 
![Screenshot 2024-05-02 at 09 51 16](https://github.com/sanger/traction-ui/assets/55585488/7cbcf1d8-27a7-497e-a80b-306742582b5d)

**Comment by stevieing** [comment]
> @stevieing This is about Pool/new page where we scan tubes in ONT pipeline which is shown in screenshot below. Does it make sense? ![Screenshot 2024-05-02 at 09 51 16](https://private-user-images.githubusercontent.com/55585488/327370883-7cbcf1d8-27a7-497e-a80b-306742582b5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDM1NTcsIm5iZiI6MTcxNDY0MzI1NywicGF0aCI6Ii81NTU4NTQ4OC8zMjczNzA4ODMtN2NiY2YxZDgtMjdhNy00OTdlLWE4MGItMzA2NzQyNTgyYjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA5NDczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyY2Y2MDE2MGY0MjA2MDRlZjI0MWVmZTNmMjY0ZjEzNGY2M2MwNTE3NTY4NGRiM2U0MmMxOTFiMWRhNDY3ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cKw17DTw6ChkMbu490tgoxKZaTfxdNqvTL1j35VmNeU)

Ah ok. I understand now. Didn't realise we could pool tubes in ONT.
