### ISSUE TITLE
DPL-998-3 As developers, we need to clean up traction-ui after Revio multiplexing work to remove any code and disable any feature flags that are used for pool and run creation/editing using data before introducing aliquots to reduce technical debt and improve maintainability.

### ISSUE THREAD

**Issue by seenanair** [sanger/traction-ui#1612]
**Describe the Housekeeping**
As developers, we need to clean up traction-ui after Revio multiplexing work to remove any code and disable any feature flags that are used for pool and run creation/editing using data before introducing aliquots to reduce technical debt and improve maintainability. 

**Things to do**

- [ ] Remove  components/pacbio/V1 folder
- [ ] Remove tests/unit/components/pacbio/V1 folder
- [ ] Remove all files suffixed with V1
          - src/views 
          - tests/unit /views
          -  tests/data
          -  tests/e2e/specs/pacbio
          -  tests/fixtures
- [ ] Remove code that handles the unintended data returned from service in pacbioPoolCreate
- [ ] Remove following feature flags
          - dpl_989_ui 
          - multiplexing_phase_2_pool_with_aliquot 
          - dpl_1113_run_well_aliquots 
          - dpl_1113_run_edit_well_aliquots

**Comment by BenTopping** [comment]
Closing as covered in https://github.com/sanger/traction-ui/issues/1605
