### ISSUE TITLE
Y24-163 - As Bioscan users we would like to be able to use the label printing page in traction to print 384 well labels so we don't have to print them individually

### ISSUE THREAD

**Issue by neilsycamore** [sanger/traction-ui#1788]
**User story**
As Bioscan users we would like to be able to use the label printing page in traction to print 384 well labels so we don't have to print them individually

Presently the Bioscan team receive their 384 well barcodes as a text list in batches of 24 which they then have to print individually. The team would like to use the bulk printing functionality within Traction however there are no 384 barcode printers listed and we would like to have aa212bc2 added to that list.

**Who are the primary contacts for this story**
Adam (al32) / Mel (melanie) / Jamie (jdl)

**Who is the nominated tester for UAT**
Adam (al32) / Mel (melanie) / Jamie (jdl)

**Acceptance criteria**
To be considered successful the solution must allow:

- A label template to print 384 plate labels
- aa212bc2 to exist as a printer in traction (update rake taks)
- A 384 plate label type in configuration

**Comment by neilsycamore** [comment]
relates to [DPL-820 BIOSCAN: Printing multiple tag barcode labels #3853](https://github.com/sanger/sequencescape/issues/3853)

**Comment by andrewsparkes** [comment]
Label printing for tag plates is part of the functionality GateKeeper provided in the past.
Gatekeeper isn't up to generating the complex tag plate sets required for Bioscan so we wrote a script to generate those plates and list out on the command line the plate barcodes generated.
But no label-printing functionality.
So really we want a Gatekeeper replacement that they can generate the tag plates we're making in the (temporary)script as well as print out the labels for them.
Seems very dodgy to me to hack this label printing into a different application (Traction).

**Comment by andrewsparkes** [comment]
Was explained at standup we have general printing page in Traction UI used by both short and long read staff to print labels. And Neil says the Bioscan script is only run once or twice a month so minimal time spent doing that. 
So I'm much less concerned as long as the users are happy that there is sufficient information on the labels.
