### ISSUE TITLE
Y24-200 - [BUG] - Unable to add a library several times to the same run.

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1819]
**Describe the bug**
Hi, I encountered a bug this week setting up a run. I had a Sequel II run that had the same libraries being run multiple times. Due to the volume tracking fields I was unable to set the run up in one go as the available volume for each library was being deducted with the first instance on the run even if edited to a the volume used for each well being sequenced.
The run in question is TRACTION-RUN-1377.
I managed to work around this issue by creating the run with each library appearing once and then editing each run to add the duplicate library and then editing again for the triplicate. It may be rare that his functionality would be used on the Revio but it should be possible to sequence the sample library/pool more than once on the same run. Maybe even being able to override once the volume has hit zero. At this point in the process we will physically have a library to load so should not be prevented from loading if library volume is 0 (but this is the best point currently to register volume of library used).
In this particular instance I have used the entire library that was available and then split out the resulting reaction mix across 2 or more cells to use up the remaining library in the most efficient way possible. So, I would be happy to set the volume correctly on the first cell for the library but for any additional cells from the same library would not need further updating.
Next week I will also be loading some of the same libraries, at this moment in time I have just estimated how much library I have used for each cell so that I don't get a zero volume error when I try to create a run. However If we decided to not proceed any further the remaining library volumes would be incorrect (without further editing).

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by stevieing** [comment]
A bit more investigation:
- if you add a library to a run and use the full volume and save it then go back and change it it does not update the available volume which means when you add the same library again it will say insufficient volume.

**Comment by BenTopping** [comment]
I think we should move available_volume off the aliquot and calculate it dynamically. Added a visualisation of some of the problems and a possible solution to this lucid chart: https://lucid.app/lucidchart/56eec268-2911-44c4-ab4b-87393e811738/edit?viewport_loc=1652%2C-1164%2C3602%2C1816%2C0_0&invitationId=inv_81ba033e-8594-44c3-a37f-fd0c07fb4803

**Comment by stevieing** [comment]
@BenTopping Reasonable idea. Do you want to create a story and link to the Lucid Chart so we can move this story to done?

**Comment by BenTopping** [comment]
@stevieing I ended up implementing this solution in this PR: https://github.com/sanger/traction-ui/pull/1849.
