### ISSUE TITLE
Y24-362 - [BUG] As a long read user Ritoza / Sophia when I create libraries in a short space of time they are printed in the wrong order which makes it more difficult to add the barcodes to the tubes correctly which can cause sample swaps

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1993]
**Describe the bug**
Y24-362 - [BUG] As a long read user Ritoza / Sophia when I create libraries in a short space of time they are printed in the wrong order which makes it more difficult to add the barcodes to the tubes correctly which can cause sample swaps.

It looks like if 2 libraries are created within the same minute then they are printed in the wrong order.

The best way to deal with this is to change the way the barcodes are printed so that that they are ordered by the Trac ID (barcode) in descending order.

This has been defined as a quality issue within long read which is an indication that it can be a cause of sample swaps.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**
![image](https://github.com/user-attachments/assets/9ae76c9f-158d-47ed-a4dc-92b36c724927)

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by harrietc52** [comment]
# Deployment

- [ ] Merge `develop` into branch
- [ ] Create a Release in the Repo 
- [ ] Note Rollback release tag for UAT
- [ ] Deploy to UAT from branch
- [ ] Merge in branch to `develop`
- [ ] Note Rollback release tag for Training
- [ ] Deploy to Training from `develop` branch
- [ ] Run Integration Suite on training
- [ ] Merge `develop` into `master`
- [ ] Deploy `master` to Prod
- [ ] Perform sanity check on Prod
