### ISSUE TITLE
GPL-323 - As a user I want to be able to view ONT samples

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#291]

**Comment by stevieing** [comment]
User story
As a Long Read user I need to be able to see a page for ONT where I can see all of the samples for that pipeline along with associated data

**Who the primary contacts are for this story**
Emma Betteridge

**Acceptance criteria**
To be considered successful the solution must allow:
1 - I need to be able to see all of the currently available samples
2 - Associated data I will need to see; sample name, traction barcode, source barcode, species name, date imported into traction
3 - I need to be able to edit associated metadata? e.g. genome size
4 - I need to see a button which will allow me to generate libraries

**Additional context**
There may be a future need to filter on priority or status.

**Comment by harrietc52** [comment]
Questions:
- What data is store in SS or SE? As oppose to Traction.. only make Traction metadata editable

**Comment by harrietc52** [comment]
Questions:
- Filter

**Comment by harrietc52** [comment]
How do I unclose!?

**Comment by stevieing** [comment]
Linked to:
[GPL-385 As a user I need to be able to create ONT samples](https://github.com/sanger/traction-service/issues/211)

**Comment by harrietc52** [comment]
View the plate with wells and samples, with tags
