### ISSUE TITLE
GPL-389 As a user I want to be able to edit ONT samples

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#293]
so I can update metadata

**Comment by harrietc52** [comment]
Questions: 
- What data is store in SS or SE? As oppose to Traction.. only make Traction metadata editable

**Comment by stevieing** [comment]
[GPL-390 As a user I need to be able to edit ONT samples](https://github.com/sanger/traction-service/issues/222)

**Comment by harrietc52** [comment]
Think this is now redundant
