### ISSUE TITLE
GPL-324 - As as user I want to be able to create ONT libraries

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#294]
A library can contain multiples samples
Each sample can have a tag
If there is more than one sample then each sample must have a tag
I need to be able to add associated metadata

**Comment by stevieing** [comment]
**User story**
As a long read user for ONT I need to be able to create libraries from samples
**Who the primary contacts are for this story**
Emma Betteridge

**Acceptance criteria**
To be considered successful the solution must allow:
1 - A library can contain multiple samples
2 - Each sample can have a tag
3 - If there is more one sample then each sample must have a uniqe tag
4 - I need to be able to add associated metadata - fragment size, concentration, volume

**Additional context**
I may need to scan the library kit barcode

**Comment by harrietc52** [comment]
Questions:
- Is a calculation of yield weight from multiple samples required?

**Comment by stevieing** [comment]
Linked to:
[GPL-386 As a user I need to be able to create ONT libraries](https://github.com/sanger/traction-service/issues/213)

**Comment by harrietc52** [comment]
- Coupled with #291 
- Samples Plate view needs to have a button that allow for library creation for the different [scenarios](https://ssg-confluence.internal.sanger.ac.uk/display/PSD/Pooling+Scenarios)
- Library tube will have a barcode
