### ISSUE TITLE
GPL-325 - As a user I want to be able to view ONT libraries

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#295]

**Comment by stevieing** [comment]
**User story**
As a long read user for ONT I need to be able to see a page where I can view all of the current libraries
**Who the primary contacts are for this story**
Emma Betteridge

**Acceptance criteria**
To be considered successful the solution must allow:
1 - I need to have a list of all the current libraries
2 - I need to be see the sample name, traction barcode, volume, concentration, fragment size, date created, genome sizes
3 - I need to be able to edit the samples and tags within the libraries

**Additional context**
I may want to see required yield which is a weighted calculation based on genome size

**Comment by harrietc52** [comment]
Questions:
- Is a calculation of yield weight from multiple samples required? (Maybe don't need to store this, only calculate it on request?)

**Comment by stevieing** [comment]
Linked to:
[GPL-386 As a user I need to be able to create ONT libraries](https://github.com/sanger/traction-service/issues/213)

**Comment by harrietc52** [comment]
View:
- library tube barcode
- library name
- plate barcode (can see this is library name?)
- wells in library. dont need to be in table, but as an extra
