### ISSUE TITLE
GPL-326 - As developers we would like to investigate creating an SVG for the ONT Gridion

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#296]

**Comment by stevieing** [comment]
**User story**
As developers we would like to investigate creating an SVG for the ONT promethion run view. as SVGs are much more flexible and scalable than tables or traditional raster images. They can be scaled up and down without losing quality and so are a better choice for responsive design. They can also reduce complexity.

**Who the primary contacts are for this story**
Stephen Inglis

**Acceptance criteria**
To be considered successful the solution must allow:
1 - A prototype of how the view would look
2 - A summary of the advantages and disadvantages of moving to SVGs.
3 - How this could be used within Vue components to be reused across other views and applications

**Additional context**
We can use the open source software Inkscape to create SVGs.

**Comment by harrietc52** [comment]
Update, required for GridION
