### ISSUE TITLE
GPL-378 As a user I need to be able to create an ONT run

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#297]

**Comment by harrietc52** [comment]
Questions:
- When are events created?
- Automation to ONT API (not MVP?)

**Comment by stevieing** [comment]
[GPL-387 As a user I need to be able to create an ONT run](https://github.com/sanger/traction-service/issues/215)

**Comment by harrietc52** [comment]
Include:
A run has a Experiment name
A run has 5 flowcells (only 4 used?)
Each flowcell has a UUID
Each flowcell has a position
Each flowcell have a library tube name

Unknowns
- Do they want to know the instrument name, to know whether it was Gridion, promethion, minion etc?
- Does a run need state pending, passed etc?
