### ISSUE TITLE
GPL-321 - As the ONT team we need to be able to receive samples from either faculty or operations

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#301]

**Comment by stevieing** [comment]
If the samples do not come through samples extraction they will come via sequencescape in a plate. Operations will then put these into tubes.
We could add this functionality to Traction.
Further investigation needed ...

**Comment by stevieing** [comment]
User story
As the long read team for ONT I need to be able to import samples to traction from either sequencescape or samples extraction because samples can be extracted at various points

**Who the primary contacts are for this story**
Emma Betteridge

Acceptance criteria
To be considered successful the solution must allow:
1 - There should be a page in Traction where I can scan multiple barcodes for samples and import those samples into traction along with the associated metadata from sequencescape
2 - There should be a page in Traction where I can scan multiple barcodes for samples and import those samples into traction along with the associated metadata from samples extraction
2 - All samples will be received in tubes

**Comment by harrietc52** [comment]
- Store sample name, species, traction barcode, source barcode, species name, date imported into traction (created at), genome size. 
- Do they want to know where plate has been sourced from, SE or SS?

**Comment by stevieing** [comment]
Linked to:
https://github.com/sanger/traction-service/issues/211
GPL-385 As a user I need to be able to create ONT samples #211

**Comment by harrietc52** [comment]
Plates will come from Sequencescape
- User inputs DN barcode from SS
- Request to fetch plate and well info, with samples and tags
- Create plate in Traction, with the DN barcode as the plates barcode
- On plate creation, plate will have many wells. Each well can have many samples. Each sample may be tagged. 

There are 4 different scenarios in how the plates will contain samples in the wells with tags:
- Scenario 1/2: there will be one sample in each well, and the samples will not be tagged
- Scenario 3/4: there will be multiple samples in each well, and the sampels will be pre tagged
