### ISSUE TITLE
GPL-380 As a user I want to be able to updatean ONT GridION run

### ISSUE THREAD

**Issue by harrietc52** [sanger/traction-ui#302]
**User story**
As a user I need to be able to edit an ONT run

**Who the primary contacts are for this story**
Steve / Harry

**Acceptance criteria**
To be considered successful the solution must allow:
1. I should be able to modify the state of a run
2. I should be able to modify which libraries are in which flowcells

**Additional context**

**Comment by harrietc52** [comment]
What are the states? Pending/ started/ completed/ cancelled?

**Comment by stevieing** [comment]
[GPL-388 As a user I need to be able to edit ONT runs](https://github.com/sanger/traction-service/issues/317)
