### ISSUE TITLE
GPL-381 As a user I want to be able to edit ONT GridION runs

### ISSUE THREAD

**Issue by harrietc52** [sanger/traction-ui#303]
User story
As a user I need to be able to edit an ONT run

Who the primary contacts are for this story
Steve / Harry

Acceptance criteria
To be considered successful the solution must allow:

    I should be able to modify the state of a run
    I should be able to modify which libraries are in which flowcells

Additional context

**Comment by stevieing** [comment]
Linked to:
[GPL-388 As a user I need to be able to edit ONT runs](https://github.com/sanger/traction-service/issues/317)

**Comment by harrietc52** [comment]
Add optional field to udpate the pore count / warrenty of a flowcell.  Integer around 13000-15000

**Comment by stevieing** [comment]
What are the states? Pending/ started/ completed/ cancelled?

**Comment by harrietc52** [comment]
branch harrietc52:GPL-378-create-ont-run
