### ISSUE TITLE
User Interface review

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#319]
Look at how we can maximise screen real estate ...
For example - create a header with title, pipeline and nav bar.

**Comment by harrietc52** [comment]
I have noticed that we are using vuex in slightly different ways in our components, views and tests. It would be great to review all of it and standardise.
(Moved from duplicate issue #320 )

**Comment by KatyTaylor** [comment]
Couple of specific things that aren't ideal currently:
- Horizontal scroll bar on the table on Runs and Libraries tabs (using a large screen)
- 'Generate Sample Sheet' button in the Runs table is styled differently from other buttons

![Screenshot 2020-08-07 at 13 36 25](https://user-images.githubusercontent.com/10407809/89646707-2eda6900-d8b4-11ea-8bb0-d5f7c8e11714.png)
![Screenshot 2020-08-07 at 13 34 43](https://user-images.githubusercontent.com/10407809/89646710-30a42c80-d8b4-11ea-8925-942dfe1d5510.png)

**Comment by stevieing** [comment]
Some of the ui issues have now been fixed but a user interface review would still be helpful.

**Comment by stevieing** [comment]
Closed in favour of work done within the team to use tailwind and remove bootstrap.
