### ISSUE TITLE
GPL-391 - As a user I want to be able to delete ONT libraries

### ISSUE THREAD

**Issue by harrietc52** [sanger/traction-ui#378]
**User story**
As a long read user for ONT I need to be able to delete ONT libraries 

**Who the primary contacts are for this story**
Emma Betteridge

**Acceptance criteria**
To be considered successful the solution must allow:
1. Must be able to delete an ONT library

**Additional context**
Confirm the above and how they would like to edit samples/ tags and what library metadata they would like to be able to edit

**Comment by harrietc52** [comment]
Questions: 
can you edit the samples in a library, or just library metadata? E.g genome size comes from SS/SE? Can you edit sample tags?

**Comment by stevieing** [comment]
[GPL-392 As a user I need to be able to edit ONT libraries](https://github.com/sanger/traction-service/issues/223)

**Comment by stevieing** [comment]
Need to be able to record the run time
