### ISSUE TITLE
GPL-396 as a developer I need integration tests for traction so we can be sure that everything works end to end

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#382]
**Description**
Research the efficacy of using cypress.io to create integration tests for traction. It should be stable, relatively simple to set up, fast and flexible and framework agnostic.

**Users**
Harreit Craven/ Stephen Inglis

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by harrietc52** [comment]
Cypress
