### ISSUE TITLE
GPL-263b As Craig I would like the ability to add a pre-extension time to the well for a run as this is required for the sample sheet and I currently have to enter it manually #268

### ISSUE THREAD

**Issue by harrietc52** [sanger/traction-ui#497]
On updating a well, select a Sequencing mode:
If the sequencing mode is CLR, Automation Parameters in the CSV is blank

If the sequencing mode is CCS, a field should appear where they can enter a pre-extension time.
Add pre-extension to a well - number field - not required

Coupled with https://github.com/sanger/traction-service/issues/268

**Comment by harrietc52** [comment]
Todo:
- [ ] Add form input for extension time, when sequencing mode is CSS
- [ ] Update validation for well status
- [ ] Add default values
- [ ] Add to CREATE run request 
- [ ] Add to UPDATE run request

**Comment by harrietc52** [comment]
branch: GPL-263b-well-extension-time

**Comment by KatyTaylor** [comment]
Questions and reply from Craig:

Katy:

> It seems like you will be mostly using a ‘pre-extension time’ with the CCS sequencing mode. Will that always be the case, or might you want to use it in the CLR mode at some point? I’m wondering whether or not to restrict it, so that it’s impossible to create wells with pre-extension times on CLR runs.
Is there conceptually a difference between ‘pre-extension time’ being not set, and it being ‘0’? I guess if you enter 0 that means you’re not using the feature and the ‘Automation Parameters’ column should be left blank on the spreadsheet?

Craig:

> 1.  Unfortunately, there will be times when we would want to use a pre-extension for CLR and as we can no longer upload sample sheets and edit I think we now need to build in a bit more flexibility in Traction.
> 2.  No, like you say, if we enter 0, it’s not being used so the cell can be blank for the well in question. It would be nice if:
a. CLR sequencing mode is selected, the default value is 0
b. CCS sequencing mode selected, the default value is 2
