### ISSUE TITLE
GPL-nnn As a long read user I would like tags to be added to a sample at amplification and indexing step

### ISSUE THREAD

**Issue by BenTopping** [sanger/traction-ui#576]
**User story**
As a long read user I would like tags to be added to a sample at amplification and indexing step for the pacbio pipeline

**Who are the primary contacts for this story**
N/A

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] When the amplification and indexing step is being done (during library creation) i should have the option to choose a tag for each sample being multiplexed

**Dependencies**
**Note** traction-service side of this story may already be supported but this is blocked until multiplexing on library creation is supported

**Additional context**

**Comment by stevieing** [comment]
This has been done as part of the multiplexing work.
