### ISSUE TITLE
GPL-nnn As a long read user I would like to see a samples status based on QC results for pre lib QC and pooling

### ISSUE THREAD

**Issue by BenTopping** [sanger/traction-ui#577]
**User story**
As a long read user I would like to see a samples status based on QC results for pre lib QC and pooling

**Who are the primary contacts for this story**
N/A

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] status of a sample should be visible in the 'Show details' drop down on the pacbio libraries page
- [ ] should be able to change the status of a sample within a library to pass/fail
   - Could do this via 'Show details' drop down on the pacbio libraries page then on edit of each sample
   - Users probably want to be able to see the samples QC results here aswell in order to make the decision

**Dependencies**
**Note**: This is dependant on status being added to samples in traction-service (covered in another IsoSeq story not yet created at time of writing)

**Additional context**

**Comment by stevieing** [comment]
This may become a priority and be covered by the automated manifests work.
