### ISSUE TITLE
GPL-nnn Pass or fail a sample

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/traction-ui#580]
**User story**
As a user of the PacBio section of Traction, I would like to be able to fail a sample based on its QC results, and for this to be visible in Traction, so that I don't accidentally take samples further down the pipeline when they should be stopped.

**Who are the primary contacts for this story**
Iraad, Craig, Emma B

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] I can fail a sample using the Traction interface
- [ ] I can see which samples have been failed
- [ ] This information is propagated to the warehouse (?)
- [ ] Failing a sample doesn't stop me from taking it through Traction a second time (as this will be a different aliquot and therefore not contaminated, for instance)

**Additional context**
This will probably also need a traction-service story.
Viewing the QC results is covered by https://github.com/sanger/traction-ui/issues/579

**Comment by stevieing** [comment]
Superceded by #613
