### ISSUE TITLE
GPL-nnn Print QC labels

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/traction-ui#581]
**User story**
As a user of the PacBio section of Traction, I would like to be able to print off extra labels for a plate or tube with a related but distinct barcode, so that the QC plates or tubes associated with it can be tracked.

**Who are the primary contacts for this story**
Iraad, Craig, Emma B

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] From a plate or tube, I can print extra QC labels
- [ ] QC labels have the original plate or tube's barcode, plus '_QC1', '_QC2' etc. on the end
- [ ] (to decide) It is configured how many QC labels will be needed for each plate / tube (alternative is just let them print however many they want, but record what the increment is up to)

**Additional context**
This will tie in with displaying QC information - https://github.com/sanger/traction-ui/issues/579

**Comment by stevieing** [comment]
@TWJW-SANGER Worth revisiting this. This may already be covered by the label printing page which would be easy to change.
