### ISSUE TITLE
GPL-nnn Handling state and firing events

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/traction-ui#582]
**Description**
As a user of the PacBio section of Traction, I would like to be able to see in the Traction UI where a sample is in the pipeline, without having a screen for each step like Limber does.

As someone who reports on Tree of Life samples, I would like to know where in the pipeline a sample is. (assuming this will use events)

**Who the primary contacts are for this work**
Iraad, Craig, Emma B

**Additional context or information**
See pipeline here - https://lucid.app/lucidchart/invitations/accept/99a2299b-24ed-463f-b658-73792f93bc77

**Comment by stevieing** [comment]
Closed as being covered by other work.
