### ISSUE TITLE
GPL-878-3 - Multiplexing - I need to be able to add samples(requests) to the pool

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#608]
**User story**
Multiplexing - I need to be able to add samples(requests) to the pool

**Who are the primary contacts for this story**
Craig / Iraad

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] I want to be able to select multiple samples and then magically add them to the pool
- [ ] Any selected samples will appear in a separate area on the page
- [ ] The sample information will include the sample name and the source
- [ ] Show a warning when a sample has been selected more than once

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
Do they need to be able to sequence a sample multiple times?

**Comment by JamesGlover** [comment]
# Plan of action
[ ] Update selected requests getter
[ ] Update select request mutations
[ ] Clicking wells should generate select request mutations
     - Will need to consider component reusability here, so will probably need to bubble up well clicked events
     - Should be a toggelable action
[ ] Selected wells should be clearly identified
[ ] Look at list view, list view should generate same events
    - May even be possible to bubble up the same event as the plate view.

**Comment by JamesGlover** [comment]
So with event stuff I'm taking the following approach:
1) The well component has a standard click event, which gets emitted to the plate. It doesn't attempt to do anything fancier as it felt wrong to start making what is essentially a circle care about the underlying data too much.
2) The plate in turn emits a clickWell event, with the well id as an argument
3) It's in `PacbioLabwareSelectedList` that we begin trying the clicking action to the actual behaviours we want.
4) But the actual logic will all exist in an action that will call the various mutations (usually just the one)

**Comment by JamesGlover** [comment]
The current approach isn't great at handling wells with multiple requests, but I don't *think* that's something we'll actually see. Will be revising this as things go on though
