### ISSUE TITLE
GPL-878-8 - Multiplexing - I want to be able to fail a sample for QC

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#613]
**User story**
I want to be able to fail a sample for QC

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] I want to be able to fail a sample for QC? Do we do this in the pool or the sample?

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by BenTopping** [comment]
Moved back to do as users want to also be able to perform QC steps alongside this:
Email from Craig: 
Yes, my understanding is this QC state needs to be applied to the sample and would be applied to samples before pooling. Highlighting the well red then indicates that the sample should not be selected for a library pool. If a sample is in a QC failed state then we would be requesting additional material (which would arrive with a different plate ID) and the current sample would not proceed any further.
 
Ideally the QC steps would be performed in a separate section in TRACTION.
 
Plate Reception -> Samples -> Sample QC -> Pool/new -> Pools -> Runs
 
The QC section would then record:
Sample volume (ul)
Sample concentration (ng/ul)
Sample Fragment size.
Sample RIN.
Sample nanodrop QC. Three separate values: 260/280, 260/230 & ng/ul
QC: PASS/FAIL
 
However, I think there was some discussion as to whether this is the correct place to record the QC information and if quanthub should be used?
 
We would also want to be able to fail a sample in a pool. i.e. the QC on sample arrival is good but when we try to do the first part of the library prep the sample does not amplify/ something else goes wrong. In the current set-up this would be on the Pool/new page – with this scenario if a sample had been selected as a fail we would want to be able to add another sample to replace the failure. We would also want to be able to add another sample to the pool that may have the same barcode as the failed sample. A sample given a failed status in the pool/New section may be repeated and allocated to a new pool at a later date.
 
At this moment in time we have the option of not selecting any failures during the library prep step (pooling/new) – there is just no way to currently record failures during the initial stage of library prep pre-pooling.
 
I don’t know how critical it is to have this as MVP – Iraad would be best to advise further but he is on holiday at the moment. I have also not performed the IsoSeq lab processes myself so have also included Karen in, just to make sure I’m not providing incorrect information to you.
