### ISSUE TITLE
DPL-137 - As A long read user I need to be able to add tags automatically to all libraries in a pool (C=M, V=4)

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#675]
**User story**
As A long read user I need to be able to add tags automatically to all libraries in a pool. For bacterial multiplexing there are 48 tags to be added for a pool. Adding these manually and will lead to higher chance of errors.

**Who are the primary contacts for this story**
Craig / Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Tagging works similar to Sequencescape with the option to override the auto populate option.
- [ ] Should be able to select multiple samples from one or more plates (No more than 48). Click and drag to select/ deselect multiple samples/ columns at a time. Don’t want to manually click up to 48 samples per pool (This would be nice for IsoSeq too)
- [ ] A tag should be selectable for each sample in the pool (manual and automatic)
- [ ] When a tag is selected the next tag in the group is associated with the next sample in the column this continues, A-H, for each column (or partial column) that was selected. If an auto filled tag is incorrect we should be able to manually correct and the autofill then continues from the new tag ID (if auto fill is selected)
- [ ] If tag#48 is reached the numbering in the plate starts back at tag#1
- [ ] There must be no duplicate tags in a pool

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by JamesGlover** [comment]
As described this doesn't quite match to the current process, as tags are applied when creating the pool, so:

- If tag#48 is reached the numbering in the plate starts back at tag#1
-  There must be no duplicate tags in a pool

Are mutually exclusive.

Also, it sounds like the second criteria:

- Should be able to select multiple samples from one or more plates (No more than 48). Click and drag to select/ deselect multiple samples/ columns at a time. Don’t want to manually click up to 48 samples per pool (This would be nice for IsoSeq too)

should also cover the addition of wells into a pool. 

Currently we populate the pool by the order in which requests were selected, whereas the tagging specifically refers to column order. So need to be a bit careful here to avoid causing too much confusion.
