### ISSUE TITLE
DPL-184 - As a user I would like to be able to edit single plexed untagged pools (C=M, V=3)

### ISSUE THREAD

**Issue by BenTopping** [sanger/traction-ui#685]
**User story**
Currently in traction you cannot edit a single-plexed untagged pool. This means if a user makes a mistake when creating an untagged library using the samples page 'create library' feature, they cannot edit the pool that the library exists in. This needs to be editable as it affects the run design these single-plexed pools are used in. 

**Who are the primary contacts for this story**
Ben T, Craig C

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Should be able to click edit on a pool with one untagged library in and it fills in the pool information with the correct info in the pools edit page.
- [ ] Should build confidence in editing single libraries through the pool page by displaying clear feedback to the user
- [ ] Should provide a link to the pool edit page from the libraries list

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by JamesGlover** [comment]
We actually *do* have an edit page for libraries (missed it earlier) but attempting tou use it results in the update button doing nothing, and us logging:
```vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in v-on handler (Promise/async): "TypeError: Cannot read properties of undefined (reading 'group_id')"

found in

---> <PacbioLibraryEdit> at src/components/pacbio/PacbioLibraryEdit.vue
       <BTr>
         <BTbody>
           <BTable>
             <Libraries> at src/views/pacbio/PacbioLibraryIndex.vue
               <PipelineView> at src/views/PipelineView.vue
                 <Pacbio> at src/views/Pacbio.vue
                   <Helper> at src/App.vue
                     <Root>
warn @ vue.runtime.esm.js?2b0e:619
vue.runtime.esm.js?2b0e:1897 TypeError: Cannot read properties of undefined (reading 'group_id')
    at _callee5$ (webpack-internal:///./src/store/traction/pacbio/libraries/actions.js:298)
    at tryCatch (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:63)
    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:294)
    at Generator.eval [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:119)
    at asyncGeneratorStep (webpack-internal:///./node_modules/@babel/runtime-corejs2/helpers/esm/asyncToGenerator.js:9)
    at _next (webpack-internal:///./node_modules/@babel/runtime-corejs2/helpers/esm/asyncToGenerator.js:31)
```

**Comment by JamesGlover** [comment]
The actual update works, its just we have a bit of a problem processing the returned payload due to missing tags.
