### ISSUE TITLE
DPL-nnn As a user I would like the ability to clone and move wells in a pacbio run (C=M, V=3) 

### ISSUE THREAD

**Issue by BenTopping** [sanger/traction-ui#687]
**User story**
As a user (Craig), It would be good to be able to copy a ‘green/ completed’ well to another well if we need to run multiple cells from the same library on the same run. Moving a well would also be useful alongside this.

**Who are the primary contacts for this story**
Craig C

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Be able to copy a well into another well in the pacbio runs view
- [ ] Be able to move a well into another well in the pacbio runs view

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
This is covered by default well attributes.
