### ISSUE TITLE
DPL-185 [BUG] - If we create a library from the samples tab it should not appear in the pools tab, especially if it is un tagged (C=3, V=3)

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#689]
**Describe the bug**
If we create a library from the samples tab it should not appear in the pools tab, especially if it is un tagged. Do we need to separate into separate library ‘inboxes’?
- Libraries tab: Single untagged libraries, a library that contains a sample with 1 tag, individual components from the pool/new tab. As it already is now
- Pools tab: Only multiplex libraries generated from the pool/new tab get listed.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by JamesGlover** [comment]
Merging into: https://github.com/sanger/traction-ui/issues/685

- Main issues here are:
  - Pools page should allow editing of untagged unplexed librairies
  - Pools page should build confidence about editing single-plexed libraries.
