### ISSUE TITLE
DPL-249 Allow cost-code customization for reception imports in traction [S]

### ISSUE THREAD

**Issue by JamesGlover** [sanger/traction-ui#699]
**User story**
As a traction UI user I would like to be able to set cost-code in bulk on import, as we can no longer rely on there being a common cost-code for TOL stuff.

>  Plates and/or Samples: Now we are going to be using TRACTION more and more we really need the option to bulk edit the cost code for the imported plates. ToL samples are now not always under the same code and if we import a plate of microbial samples we really don’t want to manually edit the cost code for 96 samples individually. This would be best to implement on the plate page as I can’t think of any manifest where samples in a plate are split across different codes.

**Who are the primary contacts for this story**
Craig C
James W

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Ability to supply a cost code when importing via reception
- [ ] Cost code should be presented in WH

**Additional context**
- From a preliminary investigation it appears that traction-service already supports cost-code being supplied by the API
- This will probably require:
  - Adding cost-code box to the bottom of the tube and plate reception pages
  - Adjusting `Pacbio.createPlates` and `Sequencescape.transformPlates` to pass in cost-code as a request attribute
- We may wish to remove the default value in traction-service

**Comment by harrietc52** [comment]
To deploy

```
ansible-playbook -vD deploy_traction_ui.yml -i environments/uat -e "github_branch=4.5.0-2101408474-develop" --check
```
