### ISSUE TITLE
DPL-250	Add error checking to Kit scanning in pacbio pipelines [S]

### ISSUE THREAD

**Issue by JamesGlover** [sanger/traction-ui#700]
**User story**
As a pacbio user I would like additional error checking added to the kit barcode options to reduce errors

>James W and I agree that we need some element of error checking with kit barcode entry/ scanning i.e. the correct barcode has been scanned for kit type i.e. library kit,  sequencing kit, binding kit etc.
Pacbio barcodes are usually in the format LOT#PRODUCT#DATE, there are generic barcodes that can be used for each kit in the following format: Lxxxxx123456789mmddyy
These are the kits currently available to use:
>
> Generic Template Prep Kit Box Barcode: Lxxxxx**100938900**123199
>
> Generic Binding Kit Box Barcode (v2.0): Lxxxxx**101789500**123199
> Generic Binding Kit Box Barcode (v2.1): Lxxxxx**101820500**123199
> Generic Binding Kit Box Barcode (v2.2):Lxxxxx**101894200**123199
>  
> Sequencing Kit BB: Lxxxxx**101826100**123199
>  
> Generic DNA Control Complex BB: Lxxxxx**101717600**123199
>  
> The nine digit string in bold can be used to validate that the correct code has been scanned.

**Who are the primary contacts for this story**
Craig C
James W

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Add validation to kit barcodes:
  - [ ] Template Prep Kit Box Barcode 
  - [ ] Binding Kit Box Barcode
  - [ ] Sequencing Kit BB
  - [ ] DNA Control Complex BB
- [ ] Invalid barcodes should be clearly flagged on scanning

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
Example formats are listed above.

**Comment by stevieing** [comment]
I think we have enough validation for now.
