### ISSUE TITLE
DPL-nnn [BUG] Traction releases don't appear to cache-bust

### ISSUE THREAD

**Issue by JamesGlover** [sanger/traction-ui#704]
**Describe the bug**
Upon making a traction release, the browser (in my case Vivaldi, but I'm assuming at least chrome) continues to serve the cached version of the assets. We should implement some form of cache busting to overcome this. Adding the release tag as a query parameter on fetching the js would probably be the easiest solution, although may be worth seeing if vue-cli provides anything to help.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by stevieing** [comment]
@JamesGlover Is this still relevant? I think you added some kind of caching?
