### ISSUE TITLE
DPL-278 - ONT Reception - Import a plate or tube from Sequencescape or Samples Extraction with a library type

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#706]
**User story**
Reception - Import a plate or tube from Sequencescape or Samples Extraction with a library type. This would require a single page with the ability to import different types of labware from multiple sources

Also see: https://github.com/sanger/traction-ui/issues/715 Which is about adding tube support to the PacBio SS reception. If we unify the receptions, then we could tackle both stories at the same time.

**Who are the primary contacts for this story**
Alex / Emma

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] The ability for the source to be Sequencescape or Samples Extraction
- [ ] The ability to scan in a list of plate and tube barcodes
- [ ] The ability to augment with additional request attributes
- [ ] The ability to override library type
- [ ] The ability to pass data to the back end sanger/traction-service#709
- [ ] The ability to dispay a receipt to the user of what has been created
- [ ] The usage of Tailwind rather than Bootstrap for styling
- [ ] The ability to support multiple pipelines

**References**
This story has a relationship with sanger/traction-service#709

**Additional context**

**Comment by JamesGlover** [comment]
Was thinking essentially traction service could provide a list of reception_sources. Each reception source would include a name, a handler, and a target URL.

The handler would exist JS side, and would generate the request to the source, and handle the response. In future the handler could even control which form gets rendered, allowing for direct CSV upload, or even an inline sample registation form.

**Comment by stevieing** [comment]
Feature flags https://www.npmjs.com/package/vue-feature-toggle
