### ISSUE TITLE
DPL-282 - ONT - create or edit a Sequencing Run

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#708]
**User story**
A Sequencing Run will be made up of one or more libraries or pools which will be assigned to one or more flowcells on either a GridIon or Promethion

**Who are the primary contacts for this story**
Alex / Emma

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Page which is similar in structure to the Pacbio run creation page
- [x] Addition of pools onto flowcells
- [x] Addition of top level run data e.g. experiment name and instument name
- [x] Addition of flowcell id to flowcell
- [ ] Bump release to v6.0

**References**
This story has a relationship with sanger/traction-service#713

**Additional context**
GridIon - 5 flowcells maximum
Promethion - 24 flowcells maximum (48 positions)

**Comment by BenTopping** [comment]
![Screenshot 2022-12-19 at 14 03 53](https://user-images.githubusercontent.com/54811755/208443319-2af62a66-651d-47f3-b66f-734beb1536b1.png)

**Comment by stevieing** [comment]
- [ ] Create a page to view the sequencing runs - similar to style to Pacbio with run id, run name, state, instrument name and created at (subject to confirmation with Long Read)
- [ ] Create a sequencing run view
- [ ] Create a component for run information which includes selecting instrument and state. Experiment name is created automatically
- [ ] Create a pool search component to allow users to select pools. The identifier will be the pool barcode.
- [ ] Create a component to view the currently selected pools
- [ ] Create a component to manage flowcells - linked to the maximum number of flowcells?
- [ ] Create a component for each flowcell
- [ ] Button to create sequencing run

**Comment by stevieing** [comment]
Vuex store for managing state:

- [ ] Runs resource
- [ ] Instruments resource
- [ ] currentRun object (see ONT pools) which would include flowcells, pools and run metadata
- [ ] actions - fetchInstruments on page load, fetchPoolByBarcode, createRun, updateRun
- [ ] state - currentRun, runs, instrument
- [ ] mutations
- [ ] getters

**Comment by BenTopping** [comment]
![Screenshot 2022-12-19 at 15 30 50](https://user-images.githubusercontent.com/54811755/208461761-cdcaff28-af26-41cc-b2b3-74bb6066421b.png)
(updated run wireframe)

**Comment by harrietc52** [comment]
Questions for UAT test

- Q: Usage: How/ When will the run be created in relation to the physical creation (upfront/ pending/ plan/ on reflection). 
**A: xx**
- Instrument: Is there a default instrument to be selected? Currently we are restricting the abilty to change the instrument type after a run has been created, is this ok?
**A: xx**
- State: Is there a default state to be selected on `create`? Can the state be changed from and to anything? Should updates be allowed for all states?
**A: xx**
- Flowcell ID: Does the flowcell ID need to be validated in any way? Can it be reused? (between a run, or any previous runs?) Does it always have the same prefix or format that can be validated?
**A: xx**
- Pool Barcode: Do you want to see any pool metadata on the flowcell? (Could add a link to Pools view?) Or is the Pools side bar list helpful.
**A: xx**
- Flowcell: Do they want a clear/reset button from Flowcell ID or Pool Barcode inputs?
**A: xx**
- Run: Do they want a Reset button for the whole run (could just navigate away from page)
**A: xx**
- Run: Might you ever need to create a Draft run
**A: xx**
- Run: Validation, should you be allowed to create a run with no flowcell data
**A: xx**
- Runs: pagination/ sort by?
**A: xx**
- ONTFlowcells: hard to use PromethION, scrolling?
**A: xx**
