### ISSUE TITLE
DPL-294 - As a team lead (Danni) I would like a Labwhere storage reception so I can see where my samples are, to provide a robust audit trail, speed up lab processes and support automation

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#714]
**User story**
This story is still required but will be used by both the ONT and Pacbio teams/samples. The requirements for this story would be to have a labwhere reception page linked to Labwhere. The location of a sample will also need be visible within Traction.

This will save time as a separate lims is not needed to complete this task. Improve sample location integrity. Provide a more robust audit trail for samples.

**Who are the primary contacts for this story**
Danni / Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] An estimate of the amount of work to add labware storage reception
- [ ] A list of well defined stories to carry out the work

**Additional context**

**Comment by stevieing** [comment]
Do we need to add a storage reception for all pipelines?

**Comment by Welly373** [comment]
This story is still required but will be used by both the ONT and Pacbio teams/samples.  The requirements for this story would be to have a labwhere reception page linked to Labwhere. The location of a sample will also need be visible within Traction. 

This will save time as a separate lims is not needed to complete this task. Improve sample location integrity. Provide a more robust audit trail for samples.

**Comment by stevieing** [comment]
https://docs.google.com/document/d/1xJLozMwUVLFEsJ-pj6NVt0lA8Te9mvItjxvyCmlso-I/edit#heading=h.fu4qqj88vkqv

**Comment by stevieing** [comment]
> @stevieing is 'Location Tracking' the correct tag for this story?

I would say so. This is all related to location tracking so I thought I would give it a standard label rather than call it Labwhere as this seems to cause confusion.
