### ISSUE TITLE
GPL-nnn Build list of used bootstrap-vue components, and include explicitly

### ISSUE THREAD

**Issue by JamesGlover** [sanger/traction-ui#826]
**Description**
- Identify all `<b-` compoinents in use
- Replace use of Vue.use(BootstrapVue) with explicit loading of required components 

**Who the primary contacts are for this work**
e.g. John Smith

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by JamesGlover** [comment]
List of all components I could find:
<b-btn
<b-modal
<b-form-select
<b-alert
<b-container
<b-row
<b-col
<b-form
<b-form-group
<b-form-input
<b-button
<b-card
<b-card-text
<b-list-group
<b-list-group-item
<b-tabs
<b-tab
<b-table
<b-badge
<b-form-checkbox
<b-form-file
<b-table-simple
<b-tr
<b-td
<b-spinner
<b-form-invalid-feedback
<b-thead
<b-th
<b-tbody
<b-img
<b-form-textarea
<b-select
<b-card-header
<b-nav
<b-nav-item
<b-card-body
<b-input-group
<b-input-group-append
<b-pagination

**Comment by JamesGlover** [comment]
I'm not quite sure what some of these are giving us over the native implementations, especially something like <b-img.

**Comment by JamesGlover** [comment]
https://bootstrap-vue.org/docs#component-groups-and-directives-as-vue-plugins

**Comment by stevieing** [comment]
> I'm not quite sure what some of these are giving us over the native implementations, especially something like <b-img.

Agreed. Always worth seeing what happens if we just remove them.
