### ISSUE TITLE
DPL-484 - Consider replacements for bootstrap-vue tables so we can remove Bootstrap and upgraded to Vue 3

### ISSUE THREAD

**Issue by JamesGlover** [sanger/traction-ui#828]
**Description**
Bootstrap-vue provides a quite extensive table component, which adds substantial behaviour:

- [ ] What behaviour are we actually using
- [ ] What libraries are available to offer similar support
- [ ] What adaptations will be needed to meet the new API

**Who the primary contacts are for this work**
Steve / Seena

**Comment by JamesGlover** [comment]
A lot of data-tables plugins are enterprise things with costly licensing:

https://www.ag-grid.com
Has a community edition. At a glance looks pretty powerful.

https://primefaces.org/primevue/datatable
Shiny and style-able, part of a much larger framework, but can be imported by itself. Wish it communicated which vue versions is supported. That said, the whole library looks pretty neat and configurable.

**Comment by stevieing** [comment]
Closed in favour of #1018
