### ISSUE TITLE
DPL-436 [BUG] Traction: edits made at run set up not always appearing in MLWH pac_bio_run table

### ISSUE THREAD

**Issue by neilsycamore** [sanger/traction-ui#852]
**Describe the bug**
We have just found out that any edits we make to run setup may not make it across to mlwarehouse automatically/ correctly.

Relates to RT [755415](https://rt.sanger.ac.uk/Ticket/Display.html?id=755415)

We accidentally duplicated a run:

TRACTION-RUN-158 & TRACTION-RUN-160.

TRACTION-RUN-160 was started with the correct samples on it.

TRACTION-RUN-158 was repurposed with different samples and updated accordingly.

Carol generated the following:
Hide quoted text
mysql> select sample.name, pac_bio_run_name run, well_label, tag_identifier from pac_bio_run, sample where pac_bio_run_name IN ('TRACTION-RUN-158','TRACTION-RUN-160') and pac_bio_run.id_sample_tmp = sample.id_sample_tmp ;
+--------------+------------------+------------+-----------------+
| name         | run              | well_label | tag_identifier  |
+--------------+------------------+------------+-----------------+
| DTOL12931477 | TRACTION-RUN-160 | A1         | bc1015_BAK8B_OA |
| DTOL12931478 | TRACTION-RUN-160 | B1         | bc1016_BAK8B_OA |
| DTOL12931479 | TRACTION-RUN-160 | C1         | bc1017_BAK8B_OA |
| DTOL12931663 | TRACTION-RUN-160 | D1         | bc1019_BAK8B_OA |
| DTOL12900725 | TRACTION-RUN-158 | A1         | bc1015_BAK8B_OA |
| DTOL12931478 | TRACTION-RUN-158 | B1         | bc1016_BAK8B_OA |
| DTOL12931479 | TRACTION-RUN-158 | C1         | bc1017_BAK8B_OA |
| DTOL12931663 | TRACTION-RUN-158 | D1         | bc1019_BAK8B_OA |
+--------------+------------------+------------+-----------------+

But should be:
+--------------+------------------+------------+-----------------+
| name | run | well_label | tag_identifier |
+--------------+------------------+------------+-----------------+
| DTOL12931477 | TRACTION-RUN-160 | A1 | bc1015_BAK8B_OA |
| DTOL12931478 | TRACTION-RUN-160 | B1 | bc1016_BAK8B_OA |
| DTOL12931479 | TRACTION-RUN-160 | C1 | bc1017_BAK8B_OA |
| DTOL12931663 | TRACTION-RUN-160 | D1 | bc1019_BAK8B_OA |
| DTOL12900725 | TRACTION-RUN-158 | A1 | bc1015_BAK8B_OA |
| DTOL12900718 | TRACTION-RUN-158 | B1 | bc1016_BAK8B_OA |
| DTOL12932860 | TRACTION-RUN-158 | C1 | bc1017_BAK8B_OA |
| DTOL12932868 | TRACTION-RUN-158 | D1 | bc1019_BAK8B_OA |
+--------------+------------------+------------+-----------------+

Samplesheets are all correct for both runs however, the information in mlwarehouse is incorrect for TRACTION-RUN-158 although well A01 appears correct. Not sure if all fields associated with traction runs are updating correctly.

Who are the primary contacts for this story
Craig C

**nts**
I re-sent the messages for the run and the pac_bio_run data was amended.
The intention is to run 'Pacbio::Run.all.each {|run| Messages.publish(run.plate, Pipelines.pacbio.message)}' @4pm today (15/07/22) as user is concerned the iRods data will be out of synch, There may be runs that are after this 4pm cut off that will need manually checking if there has been any run edits

**Comment by stevieing** [comment]
Closed as completed.
