### ISSUE TITLE
DPL-441 Update Traction well fields RT #755937

### ISSUE THREAD

**Issue by harrietc52** [sanger/traction-ui#863]
**User story**

As Craig: 
1) We need the ability to select a 10 hour movie time
2) We need to be able to enter a Pre-extension time that is not an integer (in this case 0.5)
3) After feature has been implemented, fix data as described in RT
So the data can be uploaded to SMRTLink system successfully

Both of these fields can be updated when clicking on a well, on a Run's plate. 

**Who are the primary contacts for this story**
Craig

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] For 1) 10.0 wants to be added to the movie time options and shown as an option in the "Add pool to well" model
- [ ] For 2) When adding 0.5 to Pre-extension time, after clicking modal button 'Update', no error is shown (as this button does nothing), then on Run update the error (as shown below) is displayed. A float should be accepted as a pre-extension time field type
- [ ] After feature is implemented, data as referenced in RT, has been fixed

**Dependencies**
This story is blocked by the following dependencies:
- RT #755937

**Additional context**
This story came from a ticket by Craig Corton

<img width="909" alt="Screenshot 2022-07-25 at 10 52 52" src="https://user-images.githubusercontent.com/11446617/180749957-ffc024e3-54a6-4f6b-bdce-04d8a6af33a7.png">

**Comment by BenTopping** [comment]
Closing as in done column
