### ISSUE TITLE
DPL-490 [BUG] Wrong tab highlighted after clicking top level buttons

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/traction-ui#894]
**Describe the bug**
When I use the buttons on the dashboard / home page to go to a stage of a pipeline that is not the first stage, the wrong tab is highlighted on the resulting screen.

**To Reproduce**
Steps to reproduce the behaviour:

This happens with any of the buttons, but here is one example.

1. Go to page 'Home' (top navigation bar)
2. Under the 'Saphyr' heading, click on button 'Samples'
3. Notice that, although the correct content is displayed under the tabs, the wrong tab is highlighted ('Reception' rather than 'Samples').

**Expected behaviour**
The 'Samples' tab should have been highlighted.

**Screenshots**
![Screenshot 2022-09-15 at 11 31 38](https://user-images.githubusercontent.com/10407809/190382283-e67464da-898b-4d92-b174-f8f716eaf3ef.png)

**Comment by SujitDey2022** [comment]
Moving to Ready to Deploy to Prod
