### ISSUE TITLE
DPL-491 [BUG] Bad styling on 'print labels' buttons

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/traction-ui#895]
**Describe the bug**
The modal that pops up when you click 'Print Labels' has strange styling that hides the text until you hover over the buttons (see screenshot lower down).

**To Reproduce**
Steps to reproduce the behaviour:

I think this is an issue on all equivalent pages, but here is one example.

1. Go to page 'Home' (top navigation bar)
2. Under Saphyr heading, click on button 'Samples'
3. If you don't have any sample data, see the readme 'Useful support data' section for how to create some.
4. Click on one of the table rows to select it
5. Click on button 'Print Labels'
6. See modal buttons only have visible text when you hover over them

**Expected behaviour**
Button text should always be visible.

**Screenshots**
![Screenshot 2022-09-15 at 11 43 31](https://user-images.githubusercontent.com/10407809/190384234-a493910f-b4b5-41d5-92f4-ad64addec1ee.png)

* Macbook Pro
* Chrome 105.0.5195.102 (Official Build) (x86_64)

**Comment by seenanair** [comment]
@BenTopping I have done a fix for this in branch printer-model-button-error few weeks back which was  merged to devel by Steve.
