### ISSUE TITLE
DPL-501 - As a long read user (Alex) I would like to modify the label printing page so that we can print multiple barcodes and add workflow information so we can track tubes through various pipelines so we don't have to write barcodes on the tube manually

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#901]
**User story**
As a long read user (Alex) I would like to modify the label printing page so that we can print multiple barcodes and add workflow information so we can track tubes through various pipelines so we don't have to write barcodes on the tube manually.
- currently tube labels are written manually and need to contain the following information full sample name, date of processing, step of process
- labelling is not standardised and the labels can be interpreted differently resulting in incorrect tubes being picked up for processing
- if an error occurs it is unlikely to be picked up until after sequencing
- it takes a lot of time writing the information on the label

Advantages of this approach:
- saves time - approx 15 minutes per user per process
- reduction in errors - removes ambiguity, improves labelling, reduces frustration of having to manually write on tubes
- improved sample management
- improved location tracking - barcodes will be scanned into LabWhere

Usage:
- ONT would make use of it for all stages (3-4 per sample)
- Extractions I know of at least 2 labels required per sample
- PacBio LI and ULI - 2 labels per sample
- PacBio IsoSeq - Information to be confirmed, I would have thought more than 2 labels per sample
- HiC Crosslinking - Could probably make use of 2-3 labels per sample

Forecasting
| Pipeline | Average Throughput per week | Label per sample | Total Labels per week |
| -------- | ------------------------------ | ----------------- | --------------------- | 
| PacBio Low Input | 40 | 2 | 80 |
| PacBio Ultra Low |16 | 2 | 32 |
| ONT | 2 | 3 | 6 |
| Extractions | 48 | 2 | 96 |
| HiC Crosslink | 44 | 3 | 132 |
| Total labels per week | | |  346 |

In total ~ 300-400 labels per week.

**Who are the primary contacts for this story**
Alex

**Who is the nominated tester for UAT**
Alex and the long read team

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] printing of multiple labels at once either by scanning or copying and pasting
- [x] ability to print labels without a suffix
- [x] modification of the drop down box for suffixes to include the detail of each one
- [ ] modification of the barcode text to ensure it fits on the label
- [ ] ensuring that the barcodes can be scanned into Labwhere

**Dependencies**
This story is blocked by the following dependencies:
- A list of suffixes with their descriptions

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
Follows on from RT759918

**Comment by Sangeetha-Bheeman** [comment]
Printed some labels to ensure the barcode fits on the label.
