### ISSUE TITLE
DPL-515 Include labware 'source' on labels

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/traction-ui#908]
**User story**
As a user of Traction, I would like to have a second ID (‘sample name’ or ‘source’) on the tube labels, to help identify sample swaps.

For tubes, I think the gold standard of what would be required on a label requires 4 lines and the Traction ID 2D barcode:
- Type (e.g. PacBio Library)
- ID (Traction)
- Secondary ID (Sample/Source)
- Date

Looking at the label now it looks like there is definitely room for 4 lines and a 2D barcode.

**Who are the primary contacts for this story**
James W

**Who is the nominated tester for UAT**
James W

**Acceptance criteria**
In addition to the existing information (barcode in text and 2D form)...
- [ ] Labels printed from anywhere in Traction UI (apart from the standalone Label Printing page) should have a second ID (‘sample name’ or ‘source’) added onto them.
- [ ] Labels printed from anywhere in Traction UI (apart from the standalone Label Printing page) should have the type (e.g. PacBio Library) added onto them.
- [ ] Labels printed from anywhere in Traction UI should have the date added onto them.

References
See other pending label printing improvements here - https://github.com/sanger/traction-ui/issues/901

**Additional context**
More info from Steve about the 'source' of a labware:

> All labware should have a source e.g. https://uat.traction.psd.sanger.ac.uk/#/pacbio/libraries has a source which is the plate that was originally imported. If you look in https://github.com/sanger/traction-service/blob/develop/app/resources/v1/pacbio/ they all return some kind of source identifier. They are also present in the models e.g. https://github.com/sanger/traction-service/blob/develop/app/models/pacbio/library.rb. I think it is pretty thorough. James did a piece of work to add the source so it uses some shared code. Hopefully that will make this job easier!

> In the front end it looks like source is listed in samples, libraries and pools using the same attribute.

More info about the relevant pages, that you can print labels from:
- Several of the pages that the buttons on the home page (https://uat.traction.psd.sanger.ac.uk/#/dashboard) lead to, e.g. Saphyr --> Samples, Saphyr --> Libraries, PacBio --> Samples, ... etc.

**Comment by stevieing** [comment]
This is turning out to be quite tricky. All of the printing goes through a single label creation method. I will need to refactor the whole thing. To this end the tasks are:

- [ ] new method createPrintJob in print my barcode actions which uses handleResponse correctly
- [ ] modify printer modal to accept labels method and move to use new createPrintJob method
- [ ] modify pacbio samples index view to use create labels method
- [ ] modify pacbio library index view to use create labels method or labels computed property
- [ ] modify saphyr sample index view to use create labels method or labels computed property
- [ ] modify saphyr library index to use create labels method or labels computed property
- [ ] modify label printing page to add a create labels method or labels computed property
- [ ] move current date method to library
- [ ] move any label printing specific methods back ti the label printing method
- [ ] move label printing page to use new createPrintJob method
- [ ] tidy up store to remove methods that are not needed

- [ ]
