### ISSUE TITLE
DPL-433-2 - As a user I need to be able to select the run design options based on the version

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#931]
**User story**
As a user I need to be able to select the run design options based on the version

**Who are the primary contacts for this story**
James / Craig

**Who is the nominated tester for UAT**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] When I select a smrt link version I should see the default well options for that version
- [ ] When I add a new well I should see the SMRT link version defaults and options for that version
- [ ] When I create a run it will validate the options for the selected SMRT link version

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
- [ ] Store the selected SMRT link version in the runCreate
- [ ] Add the new v11 options to the well defaults in PacbioRun
- [ ] Add the new v11 options to the updateWellPayload in PacbioRun
- [ ] Add the new v11 options to the in runs mutations
- [ ] Add the new v11 options in the PacbioRunWellDefaultEdit
- [ ] Add the new v11 options in the PacbioRunWellEdit
- [ ] Show the options for v10 or v11 based on the selected SMRT link version

**Comment by yoldas** [comment]
- [ ] Add a unit test for the provider in PacbioRunShow
- [ ] Remove redundant properties from PacbioRunInfoEdit
- [ ] Add an e2e test for creating a v10 run
- [ ] Add an e2e test for creating a v11 run
- [ ] Add an e2e test for changing version and default well options, and opening well options

**Comment by stevieing** [comment]
UAT fixes:

- [ ] Modify 5mC calls in CpG Motifs to be Include 5mC calls in CpG Motifs
- [ ] CCS Output Include low quality reads - change the default to No 
- [ ]  Barcode boxes accept whitespace and throw an error in SMRTLink - shouldn't be an issue if using a barcode scanner, but might be worth adding some kind of trim or validation?
- [ ] Demultiplex barcodes please can default be 'on instrument'
- [ ] Well information ‘On Plate Loading Concentration (mP)’ should be ‘On Plate Loading Concentration (pM)’:
