### ISSUE TITLE
DPL-543 [BUG] - As a User when I visit the runs page the data is left over from the previous run

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#940]
**Describe the bug**
As a User when I visit the runs page the data is left over from the previous run.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. If I visit the run page
2. Create a new run
3. Go back to the runs page
4. Edit a run
5. The data still shows from the previous run

**Expected behaviour**
When I create a new run the data should be empty. When I edit an existing run it should show that data. When I edit a run it should not show the data from a previously edited run.

**Screenshots**

In the following instance the run being edited is 23 but no data is showing in the run info

![Screenshot 2022-11-01 at 09 23 01](https://user-images.githubusercontent.com/519327/199202317-718e4b9d-9bd5-4ed9-a32e-e327ce4f6b63.png)
 explain your problem.

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**
It looks like the value is not set up correctly as a two way binding. Ben can provide more info

**Comment by stevieing** [comment]
Here is a list of tasks which we think need to be tackled:

- [ ] It looks like the value is not set up correctly as a two way binding. Ben can provide more info
- [ ] The placeholder is also not being shown

**Comment by seenanair** [comment]
@stevieing Thanks for the info. I had a brief chat with Ben yesterday. I think I know what's going on. I will try to fix it. There is an ITIL exam for me today afternoon. May be after that , I will look into this problem. Hope it is ok.

**Comment by stevieing** [comment]
Closed as done.
