### ISSUE TITLE
DPL-433-3 - As a developer I need to reduce the technical debt in pacbio runs as it is not setup correctly which is causing hidden bugs and issues to ensure we are Revio ready

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#941]
**User story**
As a developer I need to reduce the technical debt for pacbio runs as it is not setup correctly which is causing hidden bugs and issues. It is also not tested thoroughly or correctly in places which is making it difficult to debug. This is reducing confidence. There is also intermittent failures in the ci Cypress test. This is the only test that fails regularly.

Note: This work will also better prepare us for Revio. 

**Who are the primary contacts for this story**
Steve

**Who is the nominated tester for UAT**
PSD / Long Read

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Reorganise the vuex store so it is structured correctly
- [ ] Ensure that any asynchronous methods that are using promises handle errors correctly to ensure better user feedback
- [ ] Remove any false positive tests and replace them with working ones
- [ ] Reorganise tests to ensure that they are testing the correct things including removing any hidden asynchronous timeouts
- [ ] Move PacbioRun.js into store and reorganise it.
- [ ] Add appropriate end to end tests and modify existing ones
- [ ] Ensure that communication between store and components are correct
- [ ] Remove any object reassignment or passing objects between e.g. functions should have no side effects
- [ ] Remove any code that could lead to memory leaks e.g. Run.build receives an object and then returns that object. It should make a copy of that object before returning.
- [ ] Ensure that any promises are handled correctly
- [ ] Ensure that any functions that involve too much recursion are modified e.g. deserialize
- [ ] Add an appropriate level of documentation.
- [ ] Ensure that run creation and editing performs correctly
- [ ] Add a wrapper function/component to setup all data in store i.e. replace provide with data fetchers
- [ ] Create example payload so that front end and back end stories can be worked on independently

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
It will also be appropriate to change the service so that run creation and editing is done in a single request.

**Comment by stevieing** [comment]
Tasks to complete. Add as necessary:

- [ ] modify editRun action to use handleResponse and provide better feedback.

**Comment by SujitDey2022** [comment]
@stevieing copying in the enhancements discussed with James Watt

1. Searching for libraries to add to runs can be longwinded (discussed reversing the order as a simple fix – **Business Priority: Medium**, with a same or similar solution approach.
2. When editing run well, they should show TRAC ID as well as the well location. (User submitted this one and I’m not sure?) **Business Priority: Low**, On the new run page, when clicking a sample on the plate to edit the individual sample details, there is no confirmation of which sample is being edited. The simplest solution would be to add the Traction ID to the title of the modal popup.

**Comment by SujitDey2022** [comment]
Will cover the issue listed in https://github.com/sanger/traction-service/issues/892

**Comment by harrietc52** [comment]
Example payload to create/ update a run/ well/ pool

```
// Create

{
   "data": {
      "type": "runs",
      "attributes": {
         "sequencing_kit_box_barcode": "skbb",
         "dna_control_complex_box_barcode": "dna",
         "system_name": "Sequel II",
         "pacbio_smrt_link_version_id": 1,
         "comments": "comment 2",
         "well_attributes": [{
               "row": "A",
               "column": "1",
               "ccs_analysis_output": "Yes",
               "generate_hifi": "In SMRT Link",
               "ccs_analysis_output_include_low_quality_reads": "ccs 2",
               "include_fivemc_calls_in_cpg_motifs": "cpg",
               "ccs_analysis_output_include_kinetics_information": "ccs 3",
               "demultiplex_barcodes": "dem",
               "on_plate_loading_concentration": "oplc",
               "binding_kit_box_barcode": "bkbb",
               "pre_extension_time": "12",
               "loading_target_p1_plus_p2": "0.5",
               "movie_time": "10",
               "pools": ["6"]
            },
            {
               "row": "A",
               "column": "2",
               "ccs_analysis_output": "Yes",
               "generate_hifi": "In SMRT Link",
               "ccs_analysis_output_include_low_quality_reads": "ccs 222",
               "include_fivemc_calls_in_cpg_motifs": "cpg",
               "ccs_analysis_output_include_kinetics_information": "ccs 3333",
               "demultiplex_barcodes": "dem",
               "on_plate_loading_concentration": "oplc",
               "binding_kit_box_barcode": "bkbb",
               "pre_extension_time": "13",
               "loading_target_p1_plus_p2": "0.5",
               "movie_time": "10",
               "pools": ["7", "8"]
            }
         ]
      }
   }
}

// Update
{
   "data": {
      "id": 127,
      "type": "runs",
      "attributes": {
         "state": "started",
         "sequencing_kit_box_barcode": "skbbaaa2",
         "dna_control_complex_box_barcode": "dna2",
         "system_name": "Sequel I",
         "pacbio_smrt_link_version_id": 1,
         "comments": "comment 2aaaaa",
         "well_attributes": [{
               "id": 49,
               "row": "A",
               "column": "1",
               "ccs_analysis_output": "Yes",
               "generate_hifi": "In SMRT Link",
               "ccs_analysis_output_include_low_quality_reads": "ccs 4",
               "include_fivemc_calls_in_cpg_motifs": "cpg",
               "ccs_analysis_output_include_kinetics_information": "ccs 4",
               "demultiplex_barcodes": "dem",
               "on_plate_loading_concentration": "oplc",
               "binding_kit_box_barcode": "bkbb",
               "pre_extension_time": "12",
               "loading_target_p1_plus_p2": "0.5",
               "movie_time": "10",
               "pools": ["6"]
            },
            {
               "id": 50,
               "row": "A",
               "column": "2",
               "ccs_analysis_output": "Yes",
               "generate_hifi": "In SMRT Link",
               "ccs_analysis_output_include_low_quality_reads": "ccs 222",
               "include_fivemc_calls_in_cpg_motifs": "cpg",
               "ccs_analysis_output_include_kinetics_information": "ccs 3333",
               "demultiplex_barcodes": "dem",
               "on_plate_loading_concentration": "oplc",
               "binding_kit_box_barcode": "bkbb",
               "pre_extension_time": "13",
               "loading_target_p1_plus_p2": "0.5",
               "movie_time": "10",
               "pools": ["5"]
            }
         ]
      }
   }
}

```
