### ISSUE TITLE
DPL-538 Replace BFormSelect with a new tailwind based select component

### ISSUE THREAD

**Issue by seenanair** [sanger/traction-ui#952]
**User story**
As part of clean migration from bootstrap (DPL-483) , create a custom component to replace the bootstrap BFormSelect component

**Who are the primary contacts for this story**
Steve/Seena

**Who is the nominated tester for UAT**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:

- [ ] A new traction-select component that uses tailwind styling
- [ ] The new component should contain all existing functionalities of BFormSelect that are currently in use
- [ ] Replace all existing BFormSelect references with new component
- [ ] Remove BFormSelect from globally imported list

References
This story has a non-blocking relationship with:
- #827

**Comment by BenTopping** [comment]
Closing as in done column
