### ISSUE TITLE
DPL-583 Traction: As a user, I want to avoid saving the edited data in a modal pop-up when accidentally closing the modal window by clicking outside the modal display area

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/traction-ui#973]
**User story**
As a user, I WANT to avoid saving the edited data in a modal pop-up when accidentally closing the modal window by clicking outside the modal display area SO THAT incorrect or draft data is not saved leading to errors in calculation and reporting down the process.

**Who are the primary contacts for this story**
James Watt

**Who is the nominated tester for UAT**
James Watt

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
@BenTopping @seenanair isn't this done?

**Comment by BenTopping** [comment]
> @BenTopping @seenanair isn't this done?

Yes, just tested it. Pacbio Run Well modal data is not saved unless create/update well is clicked.
