### ISSUE TITLE
DPL-586 Traction: As a user, I want to be able to perform successful plates reception from the Sequencescape Reception tab.

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/traction-ui#977]
**Additional context**
Import library type from sequencescape doesn’t work – not sure if this is because the manifests are being filled in with library type. 
o	Can we prevent plates from being imported without a library type?
o	Can we add the ability to remove duplicate plates in Traction (if no runs/libraries are associated)?

**User story**
--

**Who are the primary contacts for this story**
e.g. James Watt

**Who is the nominated tester for UAT**
e.g.  James Watt

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Comment by stevieing** [comment]
Sequencescape reception has been removed. Does this work from the general reception if so we can close?
