### ISSUE TITLE
DPL-588 Traction: The display position and duration of the error messages on the screen need to be revisited as they currently get stacked over each other and the user has to close them manually.

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/traction-ui#980]
**User story**
The display position and duration of the error messages on the screen need to be revisited as they currently get stacked over each other and the user has to close them manually.

**Who are the primary contacts for this story**
James

**Who is the nominated tester for UAT**
James / Hermiobne 

**Acceptance criteria**

- [x] Condense alerts on pooling pages (currently on csv upload alert is created for each line)
- [ ] Condense alerts on general reception (currently on incorrect plate import the alerts can be chatty / bloated )
- [ ] Consider auto clearing alerts, alert positioning, alert size. Some pages the alerts block functionality (e.g pooling pages alerts blocking the create pool button)
- [x] Allow users to clear all alerts with an "X"

Dependencies

References

**Additional context**

![image](https://user-images.githubusercontent.com/115623404/205898699-bc91cc93-3802-42bf-ae5b-1034d7323c3a.png)

![image](https://user-images.githubusercontent.com/115623404/205899885-3bf456e9-7721-492a-8576-6dc89fb28823.png)

**Comment by stevieing** [comment]
Feedback from Craig. This should get tested by people using Traction day in, day out. However from my testing:
- Love the 'clear' button for all error messages.
- Good to have a delay, not sure if it needs to be slightly longer as errors were still stacking fairly quickly. However, the clear button resolves the main issue. Others can comment if the timing/ error message position needs to change.
