### ISSUE TITLE
DPL-591 Traction: As a user, I WANT to be able to view a visual indication that helps me know that a page or a component on the page is loading the content/data.

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/traction-ui#989]
**User story**
The clear and concise user story describing what is required. e.g. As an SSR (John D.) I would like sample manifests to allow me to upload "x" so that I can ...

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Who is the nominated tester for UAT**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by BenTopping** [comment]
@SujitDey2022 @stevieing  Can we close? All index pages now show loading spinner. Pacbio run page and pool page are the only pages that do not (to my knowledge)
